table 'Sort_Manager''s_Category'
	lineageTag: a1cbbad7-567b-4186-b07c-ab923c101d97

	column 'Manager''s category'
		dataType: string
		lineageTag: 5ed77fab-81d2-4f43-a56a-cb0cc4a6c5ea
		summarizeBy: none
		sourceColumn: Manager's category
		sortByColumn: 'Sort Order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Sort Order'
		dataType: int64
		formatString: 0
		lineageTag: 587ee289-cb55-453e-b4e9-b145c045c721
		summarizeBy: none
		sourceColumn: Sort Order

		annotation SummarizationSetBy = Automatic

	partition 'Sort_Manager''s_Category' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCghWcMvMS8xLTlXSUTJUitUBCwWXJKalAQWMwALOrv4KMaUGBkZmCq4+IUBhY4iwG1wYpt4ELOGbmleSX5SZl65gmJ9nWAwUNwWLe6akJhbDtDjn5+WlJpdk5ueBFJiBFfiXZKQWAXnmSrGxAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Alok's category" = _t, #"Soret Order" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Alok's category", type text}, {"Soret Order", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Soret Order", "Sort Order"}, {"Alok's category", "Manager's category"}})
				in
				    #"Renamed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

